spring:
  profiles:    active: dev  application:    name: item-serviceserver:  port: 8080
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  profiles: nonprod
  data:    mongodb:      host: localhost
      port: 27017
      database: local
---
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local 